### ISSUE TITLE
`make test` fails on testing branch

### ISSUE THREAD

**Issue by ajtadeo** [uclaacm/membership-portal#56]
See below error message:

```bash
membership-portal-test-backend-1  | if [ ! -f app/config/SESSION_SECRET ]; then \
membership-portal-test-backend-1  |     cat /dev/urandom | od -N 32 -t x4 -An | tr -d '\n ' > app/config/SESSION_SECRET; \
membership-portal-test-backend-1  | fi
membership-portal-test-backend-1  | yarn run v1.22.15
membership-portal-test-backend-1  | $ export TESTING=true && jest --config jest.config.json
membership-portal-test-backend-1  | PASS tests/test.tests.js
membership-portal-test-backend-1  | FAIL tests/app.api.v1.test.js
membership-portal-test-backend-1  |   ● Test suite failed to run
membership-portal-test-backend-1  | 
membership-portal-test-backend-1  |     ReferenceError: TextEncoder is not defined
membership-portal-test-backend-1  | 
membership-portal-test-backend-1  |       13 | // https://stackoverflow.com/questions/65417340/docker-compose-postgres-restart-after-running-scripts-in-docker-entrypoint-initd/65417566#65417566
membership-portal-test-backend-1  |       14 | // The DB instance managed by sequelize
membership-portal-test-backend-1  |     > 15 | const db = new Sequelize(
membership-portal-test-backend-1  |          |            ^
membership-portal-test-backend-1  |       16 |   config.database.db,
membership-portal-test-backend-1  |       17 |   config.database.user,
membership-portal-test-backend-1  |       18 |   config.database.password,
membership-portal-test-backend-1  | 
membership-portal-test-backend-1  |       at Object.<anonymous> (node_modules/pg/lib/crypto/utils-webcrypto.js:22:21)
membership-portal-test-backend-1  |       at Object.<anonymous> (node_modules/pg/lib/crypto/utils.js:8:20)
membership-portal-test-backend-1  |       at Object.<anonymous> (node_modules/pg/lib/crypto/sasl.js:2:16)
membership-portal-test-backend-1  |       at Object.<anonymous> (node_modules/pg/lib/client.js:5:12)
membership-portal-test-backend-1  |       at Object.<anonymous> (node_modules/pg/lib/index.js:3:14)
membership-portal-test-backend-1  |       at new ConnectionManager (node_modules/sequelize/lib/dialects/postgres/connection-manager.js:24:17)
membership-portal-test-backend-1  |       at new PostgresDialect (node_modules/sequelize/lib/dialects/postgres/index.js:14:30)
membership-portal-test-backend-1  |       at new Sequelize (node_modules/sequelize/lib/sequelize.js:242:20)
membership-portal-test-backend-1  |       at Object.<anonymous> (app/db/index.js:15:12)
membership-portal-test-backend-1  |       at Object.<anonymous> (app/index.js:2:7)
membership-portal-test-backend-1  |       at Object.<anonymous> (index.js:6:13)
membership-portal-test-backend-1  |       at Object.<anonymous> (tests/app.api.v1.test.js:1:1)
membership-portal-test-backend-1  | 
membership-portal-test-backend-1  | 
membership-portal-test-backend-1  | Test Suites: 1 failed, 1 passed, 2 total
membership-portal-test-backend-1  | Tests:       1 passed, 1 total
membership-portal-test-backend-1  | Snapshots:   0 total
membership-portal-test-backend-1  | Time:        9.593s
membership-portal-test-backend-1  | Ran all test suites.
membership-portal-test-backend-1  | error Command failed with exit code 1.
membership-portal-test-backend-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
membership-portal-test-backend-1 exited with code 1
```

**Comment by ajtadeo** [comment]
resolved by #57 in `testing` branch
